import StoreProvider from "./StoreProvider";
import type { Metadata } from "next";
// import { Inter, Plus_Jakarta_Sans } from "next/font/google";
import { Header, Sidebar } from "@/components";
import "./globals.css";

// const inter = Inter({ subsets: ["latin"] });
interface LayoutProps {
  children: React.ReactNode;
}
// export const metadata: Metadata = {
//   title: "Kanban Task Management App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }: LayoutProps) {
  return (
    <html lang="en">
      <StoreProvider>
        <body>
          <section className="">
            <Sidebar />
            <section>
              <Header />
              {children}
            </section>
          </section>
        </body>
      </StoreProvider>
    </html>
  );
}
